FilesKeeperWeb/Models/ErrorViewModel.cs
using System;

namespace FilesKeeperWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FilesKeeperWeb/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using FilesKeeperWeb.Services;
using FileKeeper.DAL.Models;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;

namespace FilesKeeperWeb.Controllers
{
    [Authorize]
    public class FilesController : Controller
    {
        private DataBase db;

        public FilesController(DataBase dataBase)
        {
            db = dataBase;
        }

        public IActionResult SendFiles()
        {
            return View();
        }

        public IActionResult Index()
        {
            var user = db.MRUserManager.GetUser(User.Identity.Name);
            ViewBag.Title = user.Login;
            var files = db.MRFilesManager.GetByUser(user);
            return View(files);
        }

        [HttpPost]
        //[RequestSizeLimit(50 * 1024 * 1024)]
        public IActionResult Upload(IFormFile file)
        {
            if (file.Length > (50 * 1024 * 1024)) return new BadRequestObjectResult("Слишком большой файл");

            var user = db.MRUserManager.GetUser(User.Identity.Name);
            UserFile newFile = new UserFile
            {
                Filename = file.FileName,
                UserId = user.Id,
                ContentType = file.ContentType
            };

            using (var binaryReader = new BinaryReader(file.OpenReadStream()))
            {
                newFile.Bin = binaryReader.ReadBytes((int)file.Length);
            }

            db.MRFilesManager.AddUserFile(user, newFile);
            return new OkResult();
        }

        [HttpPost]
        //[RequestSizeLimit(50 * 1024 * 1024)]
        public IActionResult AddFiles(IFormFileCollection uploads)
        {
            var user = db.MRUserManager.GetUser(User.Identity.Name);
            foreach (var file in uploads)
            {
                if (file.Length > (50 * 1024 * 1024)) return new BadRequestObjectResult(string.Format("{0} слишком большой", file.Name));

                UserFile newFile = new UserFile
                {
                    Filename = file.FileName,
                    UserId = user.Id,
                    ContentType = file.ContentType
                };

                using (var binaryReader = new BinaryReader(file.OpenReadStream()))
                {
                    newFile.Bin = binaryReader.ReadBytes((int)file.Length);
                }

                db.MRFilesManager.AddUserFile(user, newFile);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(int? id, string hash)
        {
            if (id != null)
            {
                db.MRFilesManager.DelFile((int)id, hash);
                return RedirectToAction("Index");
            }
            else
            {
                return NotFound();
            }          
        }

        [HttpPost]
        public IActionResult LoadFile(int? id, string hash)
        {
            if (id != null)
            {
                var file = db.MRFilesManager.GetFile((int)id, hash);
                return File(file.Bin, file.ContentType, file.Filename);
            }
            else
            {
                return NotFound();
            }
        }
    }
}

FilesKeeperWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FilesKeeperWeb.Models;

namespace FilesKeeperWeb.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        //public IActionResult About()
        //{
        //    ViewData["Message"] = "Your application description page.";

        //    return View();
        //}

        public IActionResult Contact()
        {
            ViewData["Message"] = "Vidilin V.A";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FilesKeeperWeb/Views/Files/Index.cshtml
@model IList<UserFile>
@*@{
            ViewData["Title"] = "Index";
    }*@



<h2>@ViewBag.Title</h2>

@*<div class="row">
        <div class="col-md-9">
            <div id="dropzone">
                <form action="/Files/Upload" class="dropzone needsclick dz-clickable" id="uploader">
                    <div class="dz-message needsclick">
                        Drop files here or click to upload.<br>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <form asp-action="AddFiles" asp-controller="Files" method="post" enctype="multipart/form-data">
            <input type="file" name="uploads" /><br>
            <input type="file" name="uploads" /><br>
            <input type="file" name="uploads" /><br>
            <input type="submit" value="Загрузить" />
        </form>*@

<p><a asp-area="" asp-controller="Files" asp-action="SendFiles" class="btn btn-default">Загрузить файлы</a></p>
@*asp-route-id="@item.Id"*@
@if (Model.Count > 0)
{
    <table class="table">
        <tr><td>Имя файла</td>@*<td>Производитель</td><td>Цена</td>*@</tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Filename
                </td>
                <td>
                    <form asp-controller="Files" asp-action="LoadFile" method="post">
                        @*<div class="form-group">*@
                            <input type="hidden" name="id" value="@item.Id">
                            <input type="hidden" name="hash" value="@item.Hash">
                            <input type="submit" class="btn btn-default" value="Скачать" />
                        @*</div>*@
                    </form>
                </td>
                <td>
                    <form asp-controller="Files" asp-action="Delete" method="post">
                        @*<div class="form-group">*@
                        <input type="hidden" name="id" value="@item.Id">
                        <input type="hidden" name="hash" value="@item.Hash">
                        <input type="submit" class="btn btn-default" value="Удалить" />
                        @*</div>*@
                    </form>
                </td>
            </tr>
        }
    </table>
}


@*<script>
        $(document).ready(function () {
            Dropzone.options.uploader = {
                paramName: "file",
                maxFilesize: 50
            };
        });
    </script>
    <link href="~/css/dropzone.css" rel="stylesheet" />
    <script src="~/bundles/dropzone.js"></script>*@

FilesKeeperWeb/Views/Files/SendFiles.cshtml
@{
    ViewData["Title"] = "SendFiles";
}

<h2>Загрузить файлы</h2>

<div class="row">
    <div class="col-md-9">
        <div id="dropzone">
            <form action="/Files/Upload" class="dropzone needsclick dz-clickable" id="uploader">
                <div class="dz-message needsclick">
                    Drop files here or click to upload.<br>
                </div>
            </form>
        </div>
    </div>
</div>

@*<form asp-action="AddFiles" asp-controller="Files" method="post" enctype="multipart/form-data">
    <input type="file" name="uploads" /><br>
    <input type="file" name="uploads" /><br>
    <input type="file" name="uploads" /><br>
    <input type="submit" value="Загрузить" />
</form>*@

<p><a asp-area="" asp-controller="Files" asp-action="Index" class="btn btn-default">Готово</a></p>

<script>
    $(document).ready(function () {
        Dropzone.options.uploader = {
            paramName: "file",
            maxFilesize: 50
        };
    });
</script>
<link href="~/css/dropzone.css" rel="stylesheet" />
<script src="~/bundles/dropzone.js"></script>

FilesKeeperWeb/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

FilesKeeperWeb/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    @*One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100*@
</address>

<address>
    <strong>Support:</strong> <a href="mailto:vidilin@yandex.com">vidilin@yandex.com</a><br />
    @*<strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>*@
</address>

FilesKeeperWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

FilesKeeperWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FilesKeeperWeb</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">FilesKeeperWeb</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @*<li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>*@
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Files" asp-action="Index">Files</a></li>
                </ul>
                <p class="nav navbar-text navbar-right">Hello, @User.Identity.Name!</p>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - FilesKeeperWeb</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>